spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/Talkera
spring.datasource.username=postgres
spring.datasource.password=yourPasword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate налаштування
spring.jpa.hibernate.ddl-auto=update
# Показувати SQL запити в консолі (щоб бачити, що відбувається)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Email configuration for Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xxx@mail.com
spring.mail.password=appPasword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Contact form settings
app.contact.recipient=xxx@mail.com

